# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'poseidon_controller_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(748, 473)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.control = QtWidgets.QWidget()
        self.control.setObjectName("control")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.control)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.line_4 = QtWidgets.QFrame(self.control)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout_6.addWidget(self.line_4, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.p2_incremental_DISP = QtWidgets.QLCDNumber(self.control)
        self.p2_incremental_DISP.setFrameShape(QtWidgets.QFrame.Panel)
        self.p2_incremental_DISP.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.p2_incremental_DISP.setDigitCount(5)
        self.p2_incremental_DISP.setObjectName("p2_incremental_DISP")
        self.gridLayout_6.addWidget(self.p2_incremental_DISP, 2, 3, 1, 1)
        self.p3_remain_DISP = QtWidgets.QLCDNumber(self.control)
        self.p3_remain_DISP.setFrameShape(QtWidgets.QFrame.Panel)
        self.p3_remain_DISP.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.p3_remain_DISP.setDigitCount(5)
        self.p3_remain_DISP.setObjectName("p3_remain_DISP")
        self.gridLayout_6.addWidget(self.p3_remain_DISP, 3, 4, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.p2_activate_CHECKBOX = QtWidgets.QCheckBox(self.control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p2_activate_CHECKBOX.sizePolicy().hasHeightForWidth())
        self.p2_activate_CHECKBOX.setSizePolicy(sizePolicy)
        self.p2_activate_CHECKBOX.setText("")
        self.p2_activate_CHECKBOX.setObjectName("p2_activate_CHECKBOX")
        self.horizontalLayout_12.addWidget(self.p2_activate_CHECKBOX)
        self.label_6 = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.gridLayout_6.addLayout(self.horizontalLayout_12, 0, 3, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_56.setFont(font)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 2, 0, 1, 1)
        self.p3_incremental_DISP = QtWidgets.QLCDNumber(self.control)
        self.p3_incremental_DISP.setFrameShape(QtWidgets.QFrame.Panel)
        self.p3_incremental_DISP.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.p3_incremental_DISP.setDigitCount(5)
        self.p3_incremental_DISP.setObjectName("p3_incremental_DISP")
        self.gridLayout_6.addWidget(self.p3_incremental_DISP, 2, 4, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.p1_activate_CHECKBOX = QtWidgets.QCheckBox(self.control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1_activate_CHECKBOX.sizePolicy().hasHeightForWidth())
        self.p1_activate_CHECKBOX.setSizePolicy(sizePolicy)
        self.p1_activate_CHECKBOX.setText("")
        self.p1_activate_CHECKBOX.setObjectName("p1_activate_CHECKBOX")
        self.horizontalLayout_14.addWidget(self.p1_activate_CHECKBOX)
        self.label_8 = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        self.gridLayout_6.addLayout(self.horizontalLayout_14, 0, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout_6.addWidget(self.label_57, 3, 0, 1, 1)
        self.p2_absolute_DISP = QtWidgets.QLCDNumber(self.control)
        self.p2_absolute_DISP.setFrameShape(QtWidgets.QFrame.Panel)
        self.p2_absolute_DISP.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.p2_absolute_DISP.setDigitCount(5)
        self.p2_absolute_DISP.setObjectName("p2_absolute_DISP")
        self.gridLayout_6.addWidget(self.p2_absolute_DISP, 1, 3, 1, 1)
        self.p1_remain_DISP = QtWidgets.QLCDNumber(self.control)
        self.p1_remain_DISP.setFrameShape(QtWidgets.QFrame.Panel)
        self.p1_remain_DISP.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.p1_remain_DISP.setDigitCount(5)
        self.p1_remain_DISP.setObjectName("p1_remain_DISP")
        self.gridLayout_6.addWidget(self.p1_remain_DISP, 3, 1, 1, 1)
        self.p1_incremental_DISP = QtWidgets.QLCDNumber(self.control)
        self.p1_incremental_DISP.setFrameShape(QtWidgets.QFrame.Panel)
        self.p1_incremental_DISP.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.p1_incremental_DISP.setDigitCount(5)
        self.p1_incremental_DISP.setObjectName("p1_incremental_DISP")
        self.gridLayout_6.addWidget(self.p1_incremental_DISP, 2, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_58.setFont(font)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_6.addWidget(self.label_58, 1, 0, 1, 1)
        self.p3_absolute_DISP = QtWidgets.QLCDNumber(self.control)
        self.p3_absolute_DISP.setFrameShape(QtWidgets.QFrame.Panel)
        self.p3_absolute_DISP.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.p3_absolute_DISP.setDigitCount(5)
        self.p3_absolute_DISP.setObjectName("p3_absolute_DISP")
        self.gridLayout_6.addWidget(self.p3_absolute_DISP, 1, 4, 1, 1)
        self.p2_remain_DISP = QtWidgets.QLCDNumber(self.control)
        self.p2_remain_DISP.setFrameShape(QtWidgets.QFrame.Panel)
        self.p2_remain_DISP.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.p2_remain_DISP.setDigitCount(5)
        self.p2_remain_DISP.setObjectName("p2_remain_DISP")
        self.gridLayout_6.addWidget(self.p2_remain_DISP, 3, 3, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.line_5 = QtWidgets.QFrame(self.control)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_13.addWidget(self.line_5)
        self.p3_activate_CHECKBOX = QtWidgets.QCheckBox(self.control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p3_activate_CHECKBOX.sizePolicy().hasHeightForWidth())
        self.p3_activate_CHECKBOX.setSizePolicy(sizePolicy)
        self.p3_activate_CHECKBOX.setText("")
        self.p3_activate_CHECKBOX.setObjectName("p3_activate_CHECKBOX")
        self.horizontalLayout_13.addWidget(self.p3_activate_CHECKBOX)
        self.label_25 = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_13.addWidget(self.label_25)
        self.gridLayout_6.addLayout(self.horizontalLayout_13, 0, 4, 1, 1)
        self.p1_absolute_DISP = QtWidgets.QLCDNumber(self.control)
        self.p1_absolute_DISP.setFrameShape(QtWidgets.QFrame.Panel)
        self.p1_absolute_DISP.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.p1_absolute_DISP.setDigitCount(4)
        self.p1_absolute_DISP.setObjectName("p1_absolute_DISP")
        self.gridLayout_6.addWidget(self.p1_absolute_DISP, 1, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_6)
        self.line_3 = QtWidgets.QFrame(self.control)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_9.addWidget(self.line_3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.p2_amount_INPUT = QtWidgets.QDoubleSpinBox(self.control)
        self.p2_amount_INPUT.setDecimals(3)
        self.p2_amount_INPUT.setMinimum(-99.0)
        self.p2_amount_INPUT.setObjectName("p2_amount_INPUT")
        self.horizontalLayout_9.addWidget(self.p2_amount_INPUT)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.p2_units_LABEL_2 = QtWidgets.QLabel(self.control)
        self.p2_units_LABEL_2.setAlignment(QtCore.Qt.AlignCenter)
        self.p2_units_LABEL_2.setObjectName("p2_units_LABEL_2")
        self.horizontalLayout_8.addWidget(self.p2_units_LABEL_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 3, 3, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.p3_amount_INPUT = QtWidgets.QDoubleSpinBox(self.control)
        self.p3_amount_INPUT.setDecimals(3)
        self.p3_amount_INPUT.setMinimum(-99.0)
        self.p3_amount_INPUT.setObjectName("p3_amount_INPUT")
        self.horizontalLayout_16.addWidget(self.p3_amount_INPUT)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.p3_units_LABEL_2 = QtWidgets.QLabel(self.control)
        self.p3_units_LABEL_2.setAlignment(QtCore.Qt.AlignCenter)
        self.p3_units_LABEL_2.setObjectName("p3_units_LABEL_2")
        self.horizontalLayout_15.addWidget(self.p3_units_LABEL_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 4, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.p1_amount_INPUT = QtWidgets.QDoubleSpinBox(self.control)
        self.p1_amount_INPUT.setDecimals(3)
        self.p1_amount_INPUT.setMinimum(-99.0)
        self.p1_amount_INPUT.setObjectName("p1_amount_INPUT")
        self.horizontalLayout_6.addWidget(self.p1_amount_INPUT)
        self.horizontalLayout.addLayout(self.horizontalLayout_6)
        self.p1_units_LABEL_2 = QtWidgets.QLabel(self.control)
        self.p1_units_LABEL_2.setAlignment(QtCore.Qt.AlignCenter)
        self.p1_units_LABEL_2.setObjectName("p1_units_LABEL_2")
        self.horizontalLayout.addWidget(self.p1_units_LABEL_2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setText("")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 4, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 2, 1, 1)
        self.p1_units_LABEL = QtWidgets.QLabel(self.control)
        self.p1_units_LABEL.setAlignment(QtCore.Qt.AlignCenter)
        self.p1_units_LABEL.setObjectName("p1_units_LABEL")
        self.gridLayout_3.addWidget(self.p1_units_LABEL, 2, 2, 1, 1)
        self.p3_syringe_LABEL = QtWidgets.QLabel(self.control)
        self.p3_syringe_LABEL.setAlignment(QtCore.Qt.AlignCenter)
        self.p3_syringe_LABEL.setObjectName("p3_syringe_LABEL")
        self.gridLayout_3.addWidget(self.p3_syringe_LABEL, 4, 1, 1, 1)
        self.p2_units_LABEL = QtWidgets.QLabel(self.control)
        self.p2_units_LABEL.setAlignment(QtCore.Qt.AlignCenter)
        self.p2_units_LABEL.setObjectName("p2_units_LABEL")
        self.gridLayout_3.addWidget(self.p2_units_LABEL, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 1, 1, 1, 1)
        self.p3_units_LABEL = QtWidgets.QLabel(self.control)
        self.p3_units_LABEL.setAlignment(QtCore.Qt.AlignCenter)
        self.p3_units_LABEL.setObjectName("p3_units_LABEL")
        self.gridLayout_3.addWidget(self.p3_units_LABEL, 4, 2, 1, 1)
        self.p2_syringe_LABEL = QtWidgets.QLabel(self.control)
        self.p2_syringe_LABEL.setAlignment(QtCore.Qt.AlignCenter)
        self.p2_syringe_LABEL.setObjectName("p2_syringe_LABEL")
        self.gridLayout_3.addWidget(self.p2_syringe_LABEL, 3, 1, 1, 1)
        self.p1_syringe_LABEL = QtWidgets.QLabel(self.control)
        self.p1_syringe_LABEL.setAlignment(QtCore.Qt.AlignCenter)
        self.p1_syringe_LABEL.setObjectName("p1_syringe_LABEL")
        self.gridLayout_3.addWidget(self.p1_syringe_LABEL, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 3, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.line = QtWidgets.QFrame(self.control)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.run_BTN = QtWidgets.QPushButton(self.control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_BTN.sizePolicy().hasHeightForWidth())
        self.run_BTN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.run_BTN.setFont(font)
        self.run_BTN.setObjectName("run_BTN")
        self.horizontalLayout_11.addWidget(self.run_BTN)
        self.pause_BTN = QtWidgets.QPushButton(self.control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_BTN.sizePolicy().hasHeightForWidth())
        self.pause_BTN.setSizePolicy(sizePolicy)
        self.pause_BTN.setObjectName("pause_BTN")
        self.horizontalLayout_11.addWidget(self.pause_BTN)
        self.zero_BTN = QtWidgets.QPushButton(self.control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero_BTN.sizePolicy().hasHeightForWidth())
        self.zero_BTN.setSizePolicy(sizePolicy)
        self.zero_BTN.setObjectName("zero_BTN")
        self.horizontalLayout_11.addWidget(self.zero_BTN)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.stop_BTN = QtWidgets.QPushButton(self.control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_BTN.sizePolicy().hasHeightForWidth())
        self.stop_BTN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stop_BTN.setFont(font)
        self.stop_BTN.setObjectName("stop_BTN")
        self.verticalLayout_2.addWidget(self.stop_BTN)
        self.line_2 = QtWidgets.QFrame(self.control)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.jog_plus_BTN = QtWidgets.QPushButton(self.control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jog_plus_BTN.sizePolicy().hasHeightForWidth())
        self.jog_plus_BTN.setSizePolicy(sizePolicy)
        self.jog_plus_BTN.setObjectName("jog_plus_BTN")
        self.verticalLayout_12.addWidget(self.jog_plus_BTN)
        self.jog_minus_BTN = QtWidgets.QPushButton(self.control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jog_minus_BTN.sizePolicy().hasHeightForWidth())
        self.jog_minus_BTN.setSizePolicy(sizePolicy)
        self.jog_minus_BTN.setObjectName("jog_minus_BTN")
        self.verticalLayout_12.addWidget(self.jog_minus_BTN)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.line_15 = QtWidgets.QFrame(self.control)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_15.setLineWidth(2)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setObjectName("line_15")
        self.horizontalLayout_4.addWidget(self.line_15)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_43 = QtWidgets.QLabel(self.control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_3.addWidget(self.label_43)
        self.absolute_RADIO = QtWidgets.QRadioButton(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.absolute_RADIO.setFont(font)
        self.absolute_RADIO.setChecked(True)
        self.absolute_RADIO.setObjectName("absolute_RADIO")
        self.verticalLayout_3.addWidget(self.absolute_RADIO)
        self.incremental_RADIO = QtWidgets.QRadioButton(self.control)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.incremental_RADIO.setFont(font)
        self.incremental_RADIO.setObjectName("incremental_RADIO")
        self.verticalLayout_3.addWidget(self.incremental_RADIO)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.control, "")
        self.camera = QtWidgets.QWidget()
        self.camera.setObjectName("camera")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.camera)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.imgLabel = QtWidgets.QLabel(self.camera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgLabel.sizePolicy().hasHeightForWidth())
        self.imgLabel.setSizePolicy(sizePolicy)
        self.imgLabel.setText("")
        self.imgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLabel.setObjectName("imgLabel")
        self.verticalLayout_11.addWidget(self.imgLabel)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.camera_connect_BTN = QtWidgets.QPushButton(self.camera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_connect_BTN.sizePolicy().hasHeightForWidth())
        self.camera_connect_BTN.setSizePolicy(sizePolicy)
        self.camera_connect_BTN.setObjectName("camera_connect_BTN")
        self.horizontalLayout_5.addWidget(self.camera_connect_BTN)
        self.camera_disconnect_BTN = QtWidgets.QPushButton(self.camera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_disconnect_BTN.sizePolicy().hasHeightForWidth())
        self.camera_disconnect_BTN.setSizePolicy(sizePolicy)
        self.camera_disconnect_BTN.setObjectName("camera_disconnect_BTN")
        self.horizontalLayout_5.addWidget(self.camera_disconnect_BTN)
        self.camera_capture_image_BTN = QtWidgets.QPushButton(self.camera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_capture_image_BTN.sizePolicy().hasHeightForWidth())
        self.camera_capture_image_BTN.setSizePolicy(sizePolicy)
        self.camera_capture_image_BTN.setObjectName("camera_capture_image_BTN")
        self.horizontalLayout_5.addWidget(self.camera_capture_image_BTN)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.camera, "")
        self.setup = QtWidgets.QWidget()
        self.setup.setObjectName("setup")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.setup)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.port_DROPDOWN = QtWidgets.QComboBox(self.setup)
        self.port_DROPDOWN.setObjectName("port_DROPDOWN")
        self.horizontalLayout_2.addWidget(self.port_DROPDOWN)
        self.refresh_ports_BTN = QtWidgets.QPushButton(self.setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh_ports_BTN.sizePolicy().hasHeightForWidth())
        self.refresh_ports_BTN.setSizePolicy(sizePolicy)
        self.refresh_ports_BTN.setObjectName("refresh_ports_BTN")
        self.horizontalLayout_2.addWidget(self.refresh_ports_BTN)
        self.verticalLayout_14.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_5 = QtWidgets.QLabel(self.setup)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_17.addWidget(self.label_5)
        self.microstepping_DROPDOWN = QtWidgets.QComboBox(self.setup)
        self.microstepping_DROPDOWN.setObjectName("microstepping_DROPDOWN")
        self.horizontalLayout_17.addWidget(self.microstepping_DROPDOWN)
        self.verticalLayout_14.addLayout(self.horizontalLayout_17)
        self.line_6 = QtWidgets.QFrame(self.setup)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_14.addWidget(self.line_6)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.p3_units_DROPDOWN = QtWidgets.QComboBox(self.setup)
        self.p3_units_DROPDOWN.setObjectName("p3_units_DROPDOWN")
        self.gridLayout.addWidget(self.p3_units_DROPDOWN, 3, 2, 1, 1)
        self.p2_units_DROPDOWN = QtWidgets.QComboBox(self.setup)
        self.p2_units_DROPDOWN.setObjectName("p2_units_DROPDOWN")
        self.gridLayout.addWidget(self.p2_units_DROPDOWN, 2, 2, 1, 1)
        self.p2_accel_INPUT = QtWidgets.QDoubleSpinBox(self.setup)
        self.p2_accel_INPUT.setMaximum(99999.99)
        self.p2_accel_INPUT.setObjectName("p2_accel_INPUT")
        self.gridLayout.addWidget(self.p2_accel_INPUT, 2, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.setup)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 4, 1, 1)
        self.p1_speed_INPUT = QtWidgets.QDoubleSpinBox(self.setup)
        self.p1_speed_INPUT.setDecimals(4)
        self.p1_speed_INPUT.setMaximum(9999.999)
        self.p1_speed_INPUT.setObjectName("p1_speed_INPUT")
        self.gridLayout.addWidget(self.p1_speed_INPUT, 1, 3, 1, 1)
        self.p2_syringe_DROPDOWN = QtWidgets.QComboBox(self.setup)
        self.p2_syringe_DROPDOWN.setObjectName("p2_syringe_DROPDOWN")
        self.gridLayout.addWidget(self.p2_syringe_DROPDOWN, 2, 1, 1, 1)
        self.p2_speed_INPUT = QtWidgets.QDoubleSpinBox(self.setup)
        self.p2_speed_INPUT.setDecimals(4)
        self.p2_speed_INPUT.setMaximum(9999.999)
        self.p2_speed_INPUT.setObjectName("p2_speed_INPUT")
        self.gridLayout.addWidget(self.p2_speed_INPUT, 2, 3, 1, 1)
        self.p1_accel_INPUT = QtWidgets.QDoubleSpinBox(self.setup)
        self.p1_accel_INPUT.setMaximum(99999.99)
        self.p1_accel_INPUT.setObjectName("p1_accel_INPUT")
        self.gridLayout.addWidget(self.p1_accel_INPUT, 1, 4, 1, 1)
        self.p3_syringe_DROPDOWN = QtWidgets.QComboBox(self.setup)
        self.p3_syringe_DROPDOWN.setObjectName("p3_syringe_DROPDOWN")
        self.gridLayout.addWidget(self.p3_syringe_DROPDOWN, 3, 1, 1, 1)
        self.p3_speed_INPUT = QtWidgets.QDoubleSpinBox(self.setup)
        self.p3_speed_INPUT.setDecimals(4)
        self.p3_speed_INPUT.setMaximum(9999.999)
        self.p3_speed_INPUT.setObjectName("p3_speed_INPUT")
        self.gridLayout.addWidget(self.p3_speed_INPUT, 3, 3, 1, 1)
        self.p1_units_DROPDOWN = QtWidgets.QComboBox(self.setup)
        self.p1_units_DROPDOWN.setObjectName("p1_units_DROPDOWN")
        self.gridLayout.addWidget(self.p1_units_DROPDOWN, 1, 2, 1, 1)
        self.p1_syringe_DROPDOWN = QtWidgets.QComboBox(self.setup)
        self.p1_syringe_DROPDOWN.setObjectName("p1_syringe_DROPDOWN")
        self.gridLayout.addWidget(self.p1_syringe_DROPDOWN, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.setup)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.setup)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.setup)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.setup)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.setup)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.setup)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 2, 1, 1)
        self.p3_accel_INPUT = QtWidgets.QDoubleSpinBox(self.setup)
        self.p3_accel_INPUT.setMaximum(99999.99)
        self.p3_accel_INPUT.setObjectName("p3_accel_INPUT")
        self.gridLayout.addWidget(self.p3_accel_INPUT, 3, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.setup)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.p1_setup_send_BTN = QtWidgets.QPushButton(self.setup)
        self.p1_setup_send_BTN.setObjectName("p1_setup_send_BTN")
        self.gridLayout.addWidget(self.p1_setup_send_BTN, 1, 6, 1, 1)
        self.p2_setup_send_BTN = QtWidgets.QPushButton(self.setup)
        self.p2_setup_send_BTN.setObjectName("p2_setup_send_BTN")
        self.gridLayout.addWidget(self.p2_setup_send_BTN, 2, 6, 1, 1)
        self.p3_setup_send_BTN = QtWidgets.QPushButton(self.setup)
        self.p3_setup_send_BTN.setObjectName("p3_setup_send_BTN")
        self.gridLayout.addWidget(self.p3_setup_send_BTN, 3, 6, 1, 1)
        self.p1_setup_jog_delta_INPUT = QtWidgets.QComboBox(self.setup)
        self.p1_setup_jog_delta_INPUT.setObjectName("p1_setup_jog_delta_INPUT")
        self.gridLayout.addWidget(self.p1_setup_jog_delta_INPUT, 1, 5, 1, 1)
        self.p2_setup_jog_delta_INPUT = QtWidgets.QComboBox(self.setup)
        self.p2_setup_jog_delta_INPUT.setObjectName("p2_setup_jog_delta_INPUT")
        self.gridLayout.addWidget(self.p2_setup_jog_delta_INPUT, 2, 5, 1, 1)
        self.p3_setup_jog_delta_INPUT = QtWidgets.QComboBox(self.setup)
        self.p3_setup_jog_delta_INPUT.setObjectName("p3_setup_jog_delta_INPUT")
        self.gridLayout.addWidget(self.p3_setup_jog_delta_INPUT, 3, 5, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.connect_BTN = QtWidgets.QPushButton(self.setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_BTN.sizePolicy().hasHeightForWidth())
        self.connect_BTN.setSizePolicy(sizePolicy)
        self.connect_BTN.setObjectName("connect_BTN")
        self.horizontalLayout_7.addWidget(self.connect_BTN)
        self.disconnect_BTN = QtWidgets.QPushButton(self.setup)
        self.disconnect_BTN.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disconnect_BTN.sizePolicy().hasHeightForWidth())
        self.disconnect_BTN.setSizePolicy(sizePolicy)
        self.disconnect_BTN.setObjectName("disconnect_BTN")
        self.horizontalLayout_7.addWidget(self.disconnect_BTN)
        self.send_all_BTN = QtWidgets.QPushButton(self.setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_all_BTN.sizePolicy().hasHeightForWidth())
        self.send_all_BTN.setSizePolicy(sizePolicy)
        self.send_all_BTN.setAcceptDrops(True)
        self.send_all_BTN.setObjectName("send_all_BTN")
        self.horizontalLayout_7.addWidget(self.send_all_BTN)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.experiment_notes = QtWidgets.QLineEdit(self.setup)
        self.experiment_notes.setObjectName("experiment_notes")
        self.verticalLayout_14.addWidget(self.experiment_notes)
        self.tabWidget.addTab(self.setup, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.status_bar_DISP = QtWidgets.QStatusBar(MainWindow)
        self.status_bar_DISP.setObjectName("status_bar_DISP")
        MainWindow.setStatusBar(self.status_bar_DISP)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 748, 22))
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.load_settings_INPUT = QtWidgets.QAction(MainWindow)
        self.load_settings_INPUT.setObjectName("load_settings_INPUT")
        self.save_settings_INPUT = QtWidgets.QAction(MainWindow)
        self.save_settings_INPUT.setObjectName("save_settings_INPUT")
        self.load_settings_BTN = QtWidgets.QAction(MainWindow)
        self.load_settings_BTN.setObjectName("load_settings_BTN")
        self.save_settings_BTN = QtWidgets.QAction(MainWindow)
        self.save_settings_BTN.setObjectName("save_settings_BTN")
        self.menuFile.addAction(self.load_settings_BTN)
        self.menuFile.addAction(self.save_settings_BTN)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Poseidon Controller"))
        self.label_6.setText(_translate("MainWindow", "Pump 2"))
        self.label_56.setText(_translate("MainWindow", "Incremental"))
        self.label_8.setText(_translate("MainWindow", "Pump 1"))
        self.label_57.setText(_translate("MainWindow", "Remain"))
        self.label_58.setText(_translate("MainWindow", "Absolute"))
        self.label_25.setText(_translate("MainWindow", "Pump 3"))
        self.p2_units_LABEL_2.setText(_translate("MainWindow", "[units]"))
        self.p3_units_LABEL_2.setText(_translate("MainWindow", "[units]"))
        self.p1_units_LABEL_2.setText(_translate("MainWindow", "[units]"))
        self.label_14.setText(_translate("MainWindow", "Pump 2"))
        self.label_15.setText(_translate("MainWindow", "Pump 3"))
        self.label_24.setText(_translate("MainWindow", "Speed"))
        self.p1_units_LABEL.setText(_translate("MainWindow", "[units]"))
        self.p3_syringe_LABEL.setText(_translate("MainWindow", "syringe"))
        self.p2_units_LABEL.setText(_translate("MainWindow", "[units]"))
        self.label_13.setText(_translate("MainWindow", "Pump 1"))
        self.label_27.setText(_translate("MainWindow", "Syringe"))
        self.p3_units_LABEL.setText(_translate("MainWindow", "[units]"))
        self.p2_syringe_LABEL.setText(_translate("MainWindow", "syringe"))
        self.p1_syringe_LABEL.setText(_translate("MainWindow", "syringe"))
        self.label_10.setText(_translate("MainWindow", "Amount "))
        self.run_BTN.setText(_translate("MainWindow", "Run"))
        self.pause_BTN.setText(_translate("MainWindow", "Pause"))
        self.zero_BTN.setText(_translate("MainWindow", "Zero"))
        self.stop_BTN.setText(_translate("MainWindow", "STOP"))
        self.jog_plus_BTN.setText(_translate("MainWindow", "Jog +"))
        self.jog_minus_BTN.setText(_translate("MainWindow", "Jog -"))
        self.label_43.setText(_translate("MainWindow", "Coord."))
        self.absolute_RADIO.setText(_translate("MainWindow", "Abs."))
        self.incremental_RADIO.setText(_translate("MainWindow", "Incr."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.control), _translate("MainWindow", "Syringe Control"))
        self.camera_connect_BTN.setText(_translate("MainWindow", "Connect"))
        self.camera_disconnect_BTN.setText(_translate("MainWindow", "Disconnect"))
        self.camera_capture_image_BTN.setText(_translate("MainWindow", "Capture Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.camera), _translate("MainWindow", "Camera"))
        self.label_7.setText(_translate("MainWindow", "Select port:"))
        self.refresh_ports_BTN.setText(_translate("MainWindow", "Refresh ports"))
        self.label_5.setText(_translate("MainWindow", "Set Microstepping:"))
        self.label_19.setText(_translate("MainWindow", "Accel"))
        self.label_16.setText(_translate("MainWindow", "Syringe"))
        self.label_20.setText(_translate("MainWindow", "Jog Delta"))
        self.label_2.setText(_translate("MainWindow", "Pump 1"))
        self.label_3.setText(_translate("MainWindow", "Pump 2"))
        self.label_18.setText(_translate("MainWindow", "Speed"))
        self.label_17.setText(_translate("MainWindow", "Units"))
        self.label_4.setText(_translate("MainWindow", "Pump 3"))
        self.p1_setup_send_BTN.setText(_translate("MainWindow", "Send"))
        self.p2_setup_send_BTN.setText(_translate("MainWindow", "Send"))
        self.p3_setup_send_BTN.setText(_translate("MainWindow", "Send"))
        self.connect_BTN.setText(_translate("MainWindow", "Connect to Controller"))
        self.disconnect_BTN.setText(_translate("MainWindow", "Disconnect from Controller"))
        self.send_all_BTN.setText(_translate("MainWindow", "Send all settings"))
        self.experiment_notes.setPlaceholderText(_translate("MainWindow", "Write notes about your experiment here. These will be appended to the end of your settings file."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setup), _translate("MainWindow", "Setup"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.load_settings_INPUT.setText(_translate("MainWindow", "Load settings"))
        self.save_settings_INPUT.setText(_translate("MainWindow", "Save settings"))
        self.load_settings_BTN.setText(_translate("MainWindow", "Load settings"))
        self.save_settings_BTN.setText(_translate("MainWindow", "Save settings"))

